baseURL = "https://yaningo.github.io/"
title = "Yann D. it me"
# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]

# Additions start here
  [Params.Navbar]
  use = false
  
  [Params.Extensions]
  use = true
  ext = ".txt" # extension to add after single page
# Additions stop here
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Yann D. Oui oui"
  [Params.Terminal]
  # Note: color scheme
  # Note: You can choose between
  # Note: hugo-theme-shell original: ["shell-powershell", "shell-ubuntu", "shell-retro"]
  # Note: gogh theme: https://mayccoll.github.io/Gogh/
#  scheme = "GruvboxDark"
  scheme = "shell-retro"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "yann"
  pcName = "the_machine"
  workDir = "mydir"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 45 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # terminalDelay = 20 : deprecated

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  # activityDelay = 5 : deprecated

  description = """
  Hello, I'm Yann!
  
  Tech Support Enthusiast / Curious Mind /
  Musician / Translator
 
  Learning. Helping. Reading. Writing.
  Music. Scripting. Philosophy. Languages.
  Connecting the dots. Psychology.
  Walking. Cooking. Meditation.
  Fixing things. Singing. Drawing.
   
  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "here_there"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["GitHub", "https://github.com/yaningo/"],
    ["Stack Overflow", "http://stackoverflow.com/users/7221104/"],
    ["Medium", "https://medium.com/@yaningo/"],
    ["LinkedIn", "https://linkedin.com/in/yndmgo/"],
    ["GitLab", "https://gitlab.com/yaningo/"],
    ["CV (pdf)", "cv_yann.pdf"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
